services:
  db:
    image: mysql:8.0
    container_name: eshop_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Heslo pre root používateľa
      MYSQL_DATABASE: eshopandrejfinal   # Meno databázy, ktorá sa vytvorí
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
